s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(star,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin1]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin3, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin5, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(qso,[u=bin6, g=bin7, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(qso,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin6, r=bin7, i=bin5, z=bin6, redshift=bin1]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(star,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin1]).
s(qso,[u=bin5, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin8, g=bin7, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin5, g=bin5, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin1]).
s(galaxy,[u=bin4, g=bin3, r=bin3, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin3, z=bin4, redshift=bin2]).
s(qso,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin7, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(star,[u=bin6, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(star,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin1]).
s(galaxy,[u=bin4, g=bin3, r=bin4, i=bin3, z=bin3, redshift=bin2]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin6, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin4, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin6, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin3, z=bin4, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(qso,[u=bin4, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin7, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin1]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin7, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin6, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(qso,[u=bin4, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin4, g=bin3, r=bin4, i=bin3, z=bin3, redshift=bin2]).
s(star,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin1]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(star,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(qso,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin5, redshift=bin3]).
s(star,[u=bin4, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin4, r=bin4, i=bin3, z=bin4, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin6, i=bin6, z=bin7, redshift=bin1]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin7, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin7, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(star,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin1]).
s(galaxy,[u=bin7, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin4, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin7, z=bin5, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin7, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin7, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(star,[u=bin6, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(qso,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin4, g=bin3, r=bin4, i=bin3, z=bin3, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin4, z=bin4, redshift=bin1]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(star,[u=bin6, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin8, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(qso,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin4, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin3, g=bin3, r=bin3, i=bin3, z=bin3, redshift=bin2]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(qso,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin3]).
s(star,[u=bin4, g=bin3, r=bin3, i=bin3, z=bin3, redshift=bin1]).
s(galaxy,[u=bin4, g=bin3, r=bin4, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin1]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(star,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin4, redshift=bin1]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(qso,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin3, r=bin3, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin7, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin2]).
s(star,[u=bin5, g=bin5, r=bin6, i=bin5, z=bin6, redshift=bin1]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin5, g=bin4, r=bin5, i=bin4, z=bin5, redshift=bin1]).
s(star,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(star,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin1]).
s(star,[u=bin5, g=bin5, r=bin5, i=bin5, z=bin5, redshift=bin1]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin5, r=bin5, i=bin4, z=bin5, redshift=bin2]).
s(star,[u=bin8, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin1]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin4, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin5, g=bin5, r=bin5, i=bin4, z=bin4, redshift=bin2]).
s(galaxy,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin7, g=bin7, r=bin7, i=bin5, z=bin6, redshift=bin3]).
s(galaxy,[u=bin6, g=bin7, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(qso,[u=bin6, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin6, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin3]).
s(galaxy,[u=bin4, g=bin3, r=bin3, i=bin3, z=bin3, redshift=bin2]).
s(galaxy,[u=bin3, g=bin2, r=bin2, i=bin2, z=bin2, redshift=bin2]).
s(galaxy,[u=bin5, g=bin4, r=bin4, i=bin4, z=bin4, redshift=bin2]).
s(qso,[u=bin6, g=bin6, r=bin7, i=bin6, z=bin7, redshift=bin3]).
s(qso,[u=bin5, g=bin6, r=bin6, i=bin6, z=bin6, redshift=bin3]).
s(qso,[u=bin7, g=bin6, r=bin6, i=bin6, z=bin7, redshift=bin3]).
s(galaxy,[u=bin7, g=bin6, r=bin6, i=bin5, z=bin5, redshift=bin2]).
s(galaxy,[u=bin7, g=bin6, r=bin7, i=bin5, z=bin6, redshift=bin3]).
