e(qso, [alpha=bin3,delta=bin6,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin3,u=bin4,g=bin3,r=bin3,i=bin3,z=bin4,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin2,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin3,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin1,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin3,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin5,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin5,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin4,delta=bin3,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin5,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin4,delta=bin4,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin6,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin2,r=bin3,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin1,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin1,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin3,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin4,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin4,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin2,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin2,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin4,delta=bin4,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin5,delta=bin5,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin3,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin1,delta=bin3,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin5,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin4,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin5,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin5,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin6,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin3,u=bin4,g=bin4,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin2,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin2,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin5,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin1,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin4,delta=bin3,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin1]).
e(qso, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin5,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin2,delta=bin4,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin5,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin6,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin4,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin2,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin6,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin5,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin3,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin3,delta=bin3,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin1,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(star, [alpha=bin5,delta=bin5,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin5,u=bin2,g=bin2,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin2,delta=bin4,u=bin4,g=bin3,r=bin3,i=bin3,z=bin4,redshift=bin1]).
e(qso, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin3,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(star, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(galaxy, [alpha=bin5,delta=bin4,u=bin2,g=bin1,r=bin1,i=bin1,z=bin1,redshift=bin2]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin2,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin5,delta=bin4,u=bin4,g=bin4,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin5,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin5,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin4,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin4,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(galaxy, [alpha=bin3,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(qso, [alpha=bin4,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin2,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(galaxy, [alpha=bin6,delta=bin4,u=bin4,g=bin4,r=bin4,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin1,delta=bin5,u=bin4,g=bin3,r=bin4,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin3,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(galaxy, [alpha=bin3,delta=bin5,u=bin4,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(qso, [alpha=bin3,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin6,delta=bin4,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(qso, [alpha=bin4,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin4,redshift=bin3]).
e(qso, [alpha=bin6,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin3]).
e(star, [alpha=bin5,delta=bin5,u=bin2,g=bin2,r=bin2,i=bin2,z=bin2,redshift=bin1]).
e(galaxy, [alpha=bin5,delta=bin5,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin2]).
e(star, [alpha=bin1,delta=bin4,u=bin3,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
e(star, [alpha=bin1,delta=bin4,u=bin2,g=bin3,r=bin3,i=bin3,z=bin3,redshift=bin1]).
